"""Generate formal M4 aggregate artifacts without external dependencies."""
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"


def esc(s):
    return str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def chart(rows, metric, title, ylabel, out):
    modes = ["SYNC", "ASYNC_FIFO", "ASYNC_LATEST"]
    colors = {"SYNC": "#2563eb", "ASYNC_FIFO": "#dc2626", "ASYNC_LATEST": "#059669"}
    width, height, left, right, top, bottom = 840, 480, 85, 35, 55, 80
    xs = sorted({r["latency_ms"] for r in rows})
    vals = [float(r[metric]) for r in rows]
    lo, hi = min(0.0, min(vals)), max(vals)
    if hi <= lo: hi = lo + 1
    pad = (hi - lo) * .08
    lo, hi = lo - pad, hi + pad
    x = lambda v: left + (width-left-right)*(v-xs[0])/(xs[-1]-xs[0] or 1)
    y = lambda v: top + (height-top-bottom)*(hi-v)/(hi-lo)
    parts = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">', '<rect width="100%" height="100%" fill="white"/>', f'<text x="{left}" y="28" font-family="sans-serif" font-size="19" font-weight="bold">{esc(title)}</text>']
    for i in range(6):
        v = lo + (hi-lo)*i/5; yy = y(v)
        parts.append(f'<line x1="{left}" y1="{yy:.1f}" x2="{width-right}" y2="{yy:.1f}" stroke="#e5e7eb"/><text x="{left-8}" y="{yy+4:.1f}" text-anchor="end" font-family="sans-serif" font-size="11">{v:.1f}</text>')
    for v in xs: parts.append(f'<text x="{x(v):.1f}" y="{height-bottom+24}" text-anchor="middle" font-family="sans-serif" font-size="11">{v}</text>')
    parts.append(f'<line x1="{left}" y1="{height-bottom}" x2="{width-right}" y2="{height-bottom}" stroke="#374151"/><line x1="{left}" y1="{top}" x2="{left}" y2="{height-bottom}" stroke="#374151"/><text x="{(left+width-right)/2}" y="{height-24}" text-anchor="middle" font-family="sans-serif" font-size="13">configured policy latency (ms)</text><text x="20" y="{(top+height-bottom)/2}" transform="rotate(-90 20 {(top+height-bottom)/2})" text-anchor="middle" font-family="sans-serif" font-size="13">{esc(ylabel)}</text>')
    for n, mode in enumerate(modes):
        pts = sorted((r for r in rows if r["mode"] == mode), key=lambda r:r["latency_ms"])
        points = ' '.join(f'{x(r["latency_ms"]):.1f},{y(float(r[metric])):.1f}' for r in pts)
        parts.append(f'<polyline points="{points}" fill="none" stroke="{colors[mode]}" stroke-width="2.5"/>')
        for r in pts: parts.append(f'<circle cx="{x(r["latency_ms"]):.1f}" cy="{y(float(r[metric])):.1f}" r="3.5" fill="{colors[mode]}"/>')
        lx = left + n*175; parts.append(f'<line x1="{lx}" y1="{height-52}" x2="{lx+20}" y2="{height-52}" stroke="{colors[mode]}" stroke-width="3"/><text x="{lx+27}" y="{height-47}" font-family="sans-serif" font-size="12">{mode}</text>')
    parts.append('</svg>'); out.write_text('\n'.join(parts), encoding='utf-8')


def main():
    rows = json.loads((RESULTS / "m4_summary.json").read_text())
    rows = sorted(rows, key=lambda r:(r["mode"], r["latency_ms"]))
    required = {"SYNC", "ASYNC_FIFO", "ASYNC_LATEST"}
    complete = len(rows) == 18 and {r["mode"] for r in rows} == required and {r["latency_ms"] for r in rows} == {0,25,50,100,200,400}
    fieldnames = list(rows[0])
    with (RESULTS / "m4_formal_aggregate.csv").open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames); w.writeheader(); w.writerows(rows)
    evidence = {
        "formal": True, "raw_configuration_count": len(rows), "complete_matrix": complete,
        "modes": sorted(required), "latencies_ms": [0,25,50,100,200,400],
        "source": "m4_summary.json generated by clean CPU-only rerun; interrupted 20260829 artifacts excluded",
        "verdict": "PASS" if complete else "INCOMPLETE",
    }
    (RESULTS / "m4_formal_verdict.json").write_text(json.dumps(evidence, indent=2) + "\n")
    figs = RESULTS / "figures"; figs.mkdir(exist_ok=True)
    chart(rows, "success", "M4 closed-loop success vs policy latency", "mean success rate", figs / "m4_success_vs_latency.svg")
    chart(rows, "action_age_p95_ms", "M4 p95 action age vs policy latency", "p95 action age (ms)", figs / "m4_action_age_p95.svg")
    chart(rows, "max_observation_queue_depth", "M4 maximum observation queue depth", "max queue depth", figs / "m4_observation_queue_depth.svg")
    print(json.dumps(evidence))


if __name__ == "__main__": main()
